<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>c836ac06-625f-44a6-9301-a9db156ba9f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remove-sauce-labs-bike-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='remove-sauce-labs-bike-light']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4ab08f4-c8ab-479b-97c6-11f410808347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_secondary btn_small btn_inventory</value>
      <webElementGuid>e6aaa8fc-318a-4998-a331-210183cf98cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>remove-sauce-labs-bike-light</value>
      <webElementGuid>e5ee0586-3b7d-4581-80bb-f180315a871f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remove-sauce-labs-bike-light</value>
      <webElementGuid>6d26fd16-9ad1-4590-b875-d15435b53098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remove-sauce-labs-bike-light</value>
      <webElementGuid>d29e2f37-3ecc-4fed-98db-6a829bb46379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>065046f2-8bad-478b-b5e0-113cb931c6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remove-sauce-labs-bike-light&quot;)</value>
      <webElementGuid>a5ba2029-f4e0-46ef-8129-a50433263bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='remove-sauce-labs-bike-light']</value>
      <webElementGuid>8f893750-c4ce-4948-bd4c-c6ff7e133291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_container']/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>b524de6b-be3d-4fd4-858f-e09e8b5bb37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$9.99'])[1]/following::button[1]</value>
      <webElementGuid>10376aeb-f23d-4c00-af87-1128b5a63db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Bike Light'])[1]/following::button[1]</value>
      <webElementGuid>0402c2e2-0e58-4f67-8e86-ad58145ecd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Bolt T-Shirt'])[1]/preceding::button[1]</value>
      <webElementGuid>f5083a27-6043-4d98-8a3e-9152a6a380e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$15.99'])[1]/preceding::button[1]</value>
      <webElementGuid>fc189873-f92e-473b-a95b-35713a859c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/button</value>
      <webElementGuid>12fc6ca2-783f-4de9-a7ca-f10315e78449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'remove-sauce-labs-bike-light' and @name = 'remove-sauce-labs-bike-light' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>ef23650a-bff8-4fe9-9b25-0e06d2c411f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
